### ISSUE TITLE
Gradle sync failed: Could not find com.android.tools.build:gradle:3.0.0-alpha4.

### ISSUE THREAD

**Issue by indokely** [blocoio/android-template#1]
Gradle sync failed: Could not find com.android.tools.build:gradle:3.0.0-alpha4.
			Searched in the following locations:
			file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/3.0.0-alpha4/gradle-3.0.0-alpha4.pom
			file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/3.0.0-alpha4/gradle-3.0.0-alpha4.jar
			https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-alpha4/gradle-3.0.0-alpha4.pom
			https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-alpha4/gradle-3.0.0-alpha4.jar
			Required by:
			project :
			Consult IDE log for more details (Help | Show Log)

**Comment by diego-vieira** [comment]
https://stackoverflow.com/questions/42701773/how-update-the-gradle-to-3-4-1in-android-studio

**Comment by diego-vieira** [comment]
Use Android Studio 3.0+
