### ISSUE TITLE
Dependency updates script not working

### ISSUE THREAD

**Issue by stackunderflows** [blocoio/android-template#43]
I cloned the project, did all the renaming, but now running dependencyUpdates doesn't work. It takes a long time and says "build successful. 6 actionable tasks: 2 executed, 4 up-to-date". But it doesn't show what's up to date and what isn't, and a report file is not generated. Not sure if this is a configuration problem, a problem with the plugin itself, or something completely different. I tried using an older version of the plugin but had the same results.

**Comment by Filmaluco** [comment]
Hi @stackunderflows when you say you did all the renaming, do you mean you did it manually or did you run the renaming project (NewProjectCI)?

**Comment by stackunderflows** [comment]
Ha! I did it all manually. I was reading the readme top to bottom and didn't get to the part that tells you about doing it automatically. As I was doing it manually I thought to myself, I should make a script to automate this. It's kind of a pain.

**Comment by Filmaluco** [comment]
@stackunderflows I just did a quick test on the template everything seems to work, even the GitHub action we have is working...
any changes to the project `build.gradle.kts`? 

Can you try again with the following parameters on `tasks.withType<DependencyUpdatesTask>` inside the project `build.gradle.kts`:

```
// optional parameters
    checkForGradleUpdate = true
    outputFormatter = "html"
    outputDir = "build/dependencyUpdates"
    reportfileName = "report"
```

**Comment by stackunderflows** [comment]
Tried that but got the same result. Trying to start over and use the rename project. Readme says to open Main.kt and click Run MainKt, but there is no run MainKt button.

**Comment by Filmaluco** [comment]
If you open the project, go to Main.kt line 94 you should see something like this:

![Screenshot 2023-02-22 at 17 11 06](https://user-images.githubusercontent.com/20781703/220704112-17a98461-9268-4458-9a14-4810a9c64722.png)

You can click on left green triangle to run.
Or you can always configure it
![Screenshot 2023-02-22 at 17 12 40](https://user-images.githubusercontent.com/20781703/220704549-7cc5ef18-d4c0-4cf8-a0c6-d10c9ab8d76b.png)

**Comment by stackunderflows** [comment]
Not sure why, but I got it to work. I installed the latest MacOS update and rebooted and now it works. I also got the rename script working too. That's so much easier than manually doing it. This is really awesome. Thanks for your good work and help!
